Update GitHub Actions workflow for timetable check

diff --git a/.github/workflows/ros_ttbcheck_ci.yml b/.github/workflows/ros_ttbcheck_ci.yml
--- a/.github/workflows/ros_ttbcheck_ci.yml
+++ b/.github/workflows/ros_ttbcheck_ci.yml
@@ -5,7 +5,7 @@ jobs:
     name: Run Timetable Checker
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v7
 
       - name: Setup Python for Parsing Output
         uses: actions/setup-python@v6
@@ -18,8 +18,8 @@ jobs:
       - name: Validate Timetable
         run: |
           set -e
-          for ttb in $(find -name "*.ttb"); do
+          find -iname "*.ttb" | while read ttb; do
             echo "Validating $ttb"
-            railostools validate '$ttb' || (echo "Validation failed." && exit 1)
+            railostools validate "$ttb" || (echo "Validation failed." && exit 1)
             echo "Validation succeeded."
           done
